name: Angular CI Pipeline

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main  # Change to your primary branch if needed
  pull_request:
    branches:
      - main

# Define the jobs that will run in the pipeline
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'  # Adjust this to your Angular project's Node.js version

      # Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run unit tests
      - name: Run tests
        run: npm test

      # Build the Angular project
      - name: Build project
        run: npm run build
